/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreateLotRouteImport } from './routes/create-lot'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as KhataRouteImport } from './routes/khata'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PriceBoardRouteImport } from './routes/price-board'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RecyclerIndexRouteImport } from './routes/recycler/index'
import { Route as RecyclerFacilityRouteImport } from './routes/recycler/facility'
import { Route as RecyclerLotRouteImport } from './routes/recycler/lot'
import { Route as RecyclerLotsRouteImport } from './routes/recycler/lots'
import { Route as RecyclerOffersRouteImport } from './routes/recycler/offers'
import { Route as RecyclerPickupsRouteImport } from './routes/recycler/pickups'
import { Route as RecyclerRegisterRouteImport } from './routes/recycler/register'
import { Route as RecyclerTransactionsRouteImport } from './routes/recycler/transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateLotRoute = CreateLotRouteImport.update({
  id: '/create-lot',
  path: '/create-lot',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const KhataRoute = KhataRouteImport.update({
  id: '/khata',
  path: '/khata',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceBoardRoute = PriceBoardRouteImport.update({
  id: '/price-board',
  path: '/price-board',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclerIndexRoute = RecyclerIndexRouteImport.update({
  id: '/recycler/',
  path: '/recycler/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclerFacilityRoute = RecyclerFacilityRouteImport.update({
  id: '/recycler/facility',
  path: '/recycler/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclerLotRoute = RecyclerLotRouteImport.update({
  id: '/recycler/lot',
  path: '/recycler/lot',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclerLotsRoute = RecyclerLotsRouteImport.update({
  id: '/recycler/lots',
  path: '/recycler/lots',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclerOffersRoute = RecyclerOffersRouteImport.update({
  id: '/recycler/offers',
  path: '/recycler/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclerPickupsRoute = RecyclerPickupsRouteImport.update({
  id: '/recycler/pickups',
  path: '/recycler/pickups',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclerRegisterRoute = RecyclerRegisterRouteImport.update({
  id: '/recycler/register',
  path: '/recycler/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclerTransactionsRoute = RecyclerTransactionsRouteImport.update({
  id: '/recycler/transactions',
  path: '/recycler/transactions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-lot': typeof CreateLotRoute
  '/estimate': typeof EstimateRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/khata': typeof KhataRoute
  '/offers': typeof OffersRoute
  '/passport': typeof PassportRoute
  '/payment': typeof PaymentRoute
  '/price-board': typeof PriceBoardRoute
  '/safety': typeof SafetyRoute
  '/recycler/facility': typeof RecyclerFacilityRoute
  '/recycler/lot': typeof RecyclerLotRoute
  '/recycler/lots': typeof RecyclerLotsRoute
  '/recycler/offers': typeof RecyclerOffersRoute
  '/recycler/pickups': typeof RecyclerPickupsRoute
  '/recycler/register': typeof RecyclerRegisterRoute
  '/recycler/transactions': typeof RecyclerTransactionsRoute
  '/recycler/': typeof RecyclerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-lot': typeof CreateLotRoute
  '/estimate': typeof EstimateRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/khata': typeof KhataRoute
  '/offers': typeof OffersRoute
  '/passport': typeof PassportRoute
  '/payment': typeof PaymentRoute
  '/price-board': typeof PriceBoardRoute
  '/safety': typeof SafetyRoute
  '/recycler/facility': typeof RecyclerFacilityRoute
  '/recycler/lot': typeof RecyclerLotRoute
  '/recycler/lots': typeof RecyclerLotsRoute
  '/recycler/offers': typeof RecyclerOffersRoute
  '/recycler/pickups': typeof RecyclerPickupsRoute
  '/recycler/register': typeof RecyclerRegisterRoute
  '/recycler/transactions': typeof RecyclerTransactionsRoute
  '/recycler': typeof RecyclerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-lot': typeof CreateLotRoute
  '/estimate': typeof EstimateRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/khata': typeof KhataRoute
  '/offers': typeof OffersRoute
  '/passport': typeof PassportRoute
  '/payment': typeof PaymentRoute
  '/price-board': typeof PriceBoardRoute
  '/safety': typeof SafetyRoute
  '/recycler/facility': typeof RecyclerFacilityRoute
  '/recycler/lot': typeof RecyclerLotRoute
  '/recycler/lots': typeof RecyclerLotsRoute
  '/recycler/offers': typeof RecyclerOffersRoute
  '/recycler/pickups': typeof RecyclerPickupsRoute
  '/recycler/register': typeof RecyclerRegisterRoute
  '/recycler/transactions': typeof RecyclerTransactionsRoute
  '/recycler/': typeof RecyclerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create-lot'
    | '/estimate'
    | '/history'
    | '/home'
    | '/khata'
    | '/offers'
    | '/passport'
    | '/payment'
    | '/price-board'
    | '/safety'
    | '/recycler/facility'
    | '/recycler/lot'
    | '/recycler/lots'
    | '/recycler/offers'
    | '/recycler/pickups'
    | '/recycler/register'
    | '/recycler/transactions'
    | '/recycler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create-lot'
    | '/estimate'
    | '/history'
    | '/home'
    | '/khata'
    | '/offers'
    | '/passport'
    | '/payment'
    | '/price-board'
    | '/safety'
    | '/recycler/facility'
    | '/recycler/lot'
    | '/recycler/lots'
    | '/recycler/offers'
    | '/recycler/pickups'
    | '/recycler/register'
    | '/recycler/transactions'
    | '/recycler'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create-lot'
    | '/estimate'
    | '/history'
    | '/home'
    | '/khata'
    | '/offers'
    | '/passport'
    | '/payment'
    | '/price-board'
    | '/safety'
    | '/recycler/facility'
    | '/recycler/lot'
    | '/recycler/lots'
    | '/recycler/offers'
    | '/recycler/pickups'
    | '/recycler/register'
    | '/recycler/transactions'
    | '/recycler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateLotRoute: typeof CreateLotRoute
  EstimateRoute: typeof EstimateRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  KhataRoute: typeof KhataRoute
  OffersRoute: typeof OffersRoute
  PassportRoute: typeof PassportRoute
  PaymentRoute: typeof PaymentRoute
  PriceBoardRoute: typeof PriceBoardRoute
  SafetyRoute: typeof SafetyRoute
  RecyclerFacilityRoute: typeof RecyclerFacilityRoute
  RecyclerLotRoute: typeof RecyclerLotRoute
  RecyclerLotsRoute: typeof RecyclerLotsRoute
  RecyclerOffersRoute: typeof RecyclerOffersRoute
  RecyclerPickupsRoute: typeof RecyclerPickupsRoute
  RecyclerRegisterRoute: typeof RecyclerRegisterRoute
  RecyclerTransactionsRoute: typeof RecyclerTransactionsRoute
  RecyclerIndexRoute: typeof RecyclerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-lot': {
      id: '/create-lot'
      path: '/create-lot'
      fullPath: '/create-lot'
      preLoaderRoute: typeof CreateLotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khata': {
      id: '/khata'
      path: '/khata'
      fullPath: '/khata'
      preLoaderRoute: typeof KhataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-board': {
      id: '/price-board'
      path: '/price-board'
      fullPath: '/price-board'
      preLoaderRoute: typeof PriceBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycler/': {
      id: '/recycler/'
      path: '/recycler'
      fullPath: '/recycler/'
      preLoaderRoute: typeof RecyclerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycler/facility': {
      id: '/recycler/facility'
      path: '/recycler/facility'
      fullPath: '/recycler/facility'
      preLoaderRoute: typeof RecyclerFacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycler/lot': {
      id: '/recycler/lot'
      path: '/recycler/lot'
      fullPath: '/recycler/lot'
      preLoaderRoute: typeof RecyclerLotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycler/lots': {
      id: '/recycler/lots'
      path: '/recycler/lots'
      fullPath: '/recycler/lots'
      preLoaderRoute: typeof RecyclerLotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycler/offers': {
      id: '/recycler/offers'
      path: '/recycler/offers'
      fullPath: '/recycler/offers'
      preLoaderRoute: typeof RecyclerOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycler/pickups': {
      id: '/recycler/pickups'
      path: '/recycler/pickups'
      fullPath: '/recycler/pickups'
      preLoaderRoute: typeof RecyclerPickupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycler/register': {
      id: '/recycler/register'
      path: '/recycler/register'
      fullPath: '/recycler/register'
      preLoaderRoute: typeof RecyclerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycler/transactions': {
      id: '/recycler/transactions'
      path: '/recycler/transactions'
      fullPath: '/recycler/transactions'
      preLoaderRoute: typeof RecyclerTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateLotRoute: CreateLotRoute,
  EstimateRoute: EstimateRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  KhataRoute: KhataRoute,
  OffersRoute: OffersRoute,
  PassportRoute: PassportRoute,
  PaymentRoute: PaymentRoute,
  PriceBoardRoute: PriceBoardRoute,
  SafetyRoute: SafetyRoute,
  RecyclerFacilityRoute: RecyclerFacilityRoute,
  RecyclerLotRoute: RecyclerLotRoute,
  RecyclerLotsRoute: RecyclerLotsRoute,
  RecyclerOffersRoute: RecyclerOffersRoute,
  RecyclerPickupsRoute: RecyclerPickupsRoute,
  RecyclerRegisterRoute: RecyclerRegisterRoute,
  RecyclerTransactionsRoute: RecyclerTransactionsRoute,
  RecyclerIndexRoute: RecyclerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
